PACKAGE_NAME="secureexec-kmod"
PACKAGE_VERSION="0.0.0-dev"

BUILT_MODULE_NAME[0]="secureexec_kmod"
DEST_MODULE_LOCATION[0]="/extra"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C /lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"

AUTOINSTALL="yes"
