use serde::{Deserialize, Serialize};
use sha1::{Digest, Sha1};
use uuid::Uuid;

use super::{is_zero_u64, ContentHash};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegistryEvent {
    pub pid: u32,
    pub process_name: String,
    #[serde(default)]
    pub process_guid: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub process_start_time: Option<chrono::DateTime<chrono::Utc>>,
    pub key: String,
    pub value_name: String,
}

impl ContentHash for RegistryEvent {
    fn content_hash_update(&self, h: &mut Sha1) {
        h.update(self.pid.to_le_bytes());
        h.update(self.process_name.as_bytes());
        h.update(self.key.as_bytes());
        h.update(self.value_name.as_bytes());
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserLogonEvent {
    pub username: String,
    pub logon_type: String,
    pub source_addr: Option<String>,
}

impl ContentHash for UserLogonEvent {
    fn content_hash_update(&self, h: &mut Sha1) {
        h.update(self.username.as_bytes());
        h.update(self.logon_type.as_bytes());
        if let Some(addr) = &self.source_addr {
            h.update(addr.as_bytes());
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentLifecycleEvent {
    pub version: String,
    #[serde(default)]
    pub os: String,
    #[serde(default)]
    pub os_version: String,
    #[serde(default)]
    pub os_kernel_version: String,
}

impl ContentHash for AgentLifecycleEvent {
    fn content_hash_update(&self, h: &mut Sha1) {
        h.update(self.version.as_bytes());
        h.update(self.os.as_bytes());
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentHeartbeatEvent {
    pub uptime_secs: u64,
    pub spool_pending: u64,
    #[serde(default)]
    pub version: String,
    #[serde(default)]
    pub os: String,
    #[serde(default)]
    pub os_version: String,
    #[serde(default)]
    pub os_kernel_version: String,
    /// Current network isolation state.
    #[serde(default)]
    pub net_isolated: bool,
    /// True if `/dev/secureexec_kmod` was present at agent startup.
    #[serde(default)]
    pub kmod_available: bool,
    /// Active firewall backend: `"ebpf"`, `"kmod"`, or `""` (none).
    #[serde(default)]
    pub firewall_backend: String,
    /// Loaded kmod version from `/sys/module/secureexec_kmod/version`, or `""` if not loaded.
    #[serde(default)]
    pub kmod_version: String,
    /// Cumulative eBPF ring-buffer drop counts (0 on non-Linux platforms).
    #[serde(default)]
    pub ebpf_drops_process: u64,
    #[serde(default)]
    pub ebpf_drops_file: u64,
    #[serde(default)]
    pub ebpf_drops_network: u64,
    #[serde(default)]
    pub ebpf_drops_security: u64,
}

impl ContentHash for AgentHeartbeatEvent {
    fn content_hash_update(&self, h: &mut Sha1) {
        h.update(self.uptime_secs.to_le_bytes());
        h.update(self.spool_pending.to_le_bytes());
        h.update(self.version.as_bytes());
        h.update(&[self.net_isolated as u8]);
        h.update(&[self.kmod_available as u8]);
        h.update(self.firewall_backend.as_bytes());
        h.update(self.kmod_version.as_bytes());
        h.update(self.ebpf_drops_process.to_le_bytes());
        h.update(self.ebpf_drops_file.to_le_bytes());
        h.update(self.ebpf_drops_network.to_le_bytes());
        h.update(self.ebpf_drops_security.to_le_bytes());
    }
}

// ---------------------------------------------------------------------------
// Detection events — generated by the detection engine, not by sensors
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Severity {
    Low,
    Medium,
    High,
    Critical,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectionEvent {
    pub rule_name: String,
    pub severity: Severity,
    pub description: String,
    /// IDs of the source events that triggered this detection.
    pub source_event_ids: Vec<Uuid>,
    /// PID of the process involved, if any.
    #[serde(default)]
    pub pid: Option<u32>,
    #[serde(default)]
    pub process_guid: String,
}

impl ContentHash for DetectionEvent {
    fn content_hash_update(&self, h: &mut Sha1) {
        h.update(self.rule_name.as_bytes());
        h.update(self.description.as_bytes());
        for id in &self.source_event_ids {
            h.update(id.as_bytes());
        }
        if let Some(pid) = self.pid {
            h.update(pid.to_le_bytes());
        }
    }
}

/// A process execution that was blocked by a blocklist rule.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessBlockedEvent {
    pub pid: u32,
    #[serde(default)]
    pub user_id: String,
    pub process_name: String,
    #[serde(default)]
    pub process_guid: String,
    /// Absolute path of the executable that was blocked.
    pub path: String,
    /// SHA-256 hex digest of the blocked binary (empty when path-matched before hashing).
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub exe_hash: String,
    #[serde(default, skip_serializing_if = "is_zero_u64")]
    pub exe_size: u64,
    /// Human-readable name of the blocklist rule that matched.
    pub rule_name: String,
    /// Discriminator: "hash" or "path".
    pub match_type: String,
    /// The exact value that matched (hash hex or path string).
    pub match_value: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub cmdline: String,
}

impl ContentHash for ProcessBlockedEvent {
    fn content_hash_update(&self, h: &mut Sha1) {
        h.update(self.pid.to_le_bytes());
        h.update(self.user_id.as_bytes());
        h.update(self.process_name.as_bytes());
        h.update(self.process_guid.as_bytes());
        h.update(self.path.as_bytes());
        h.update(self.exe_hash.as_bytes());
        h.update(self.exe_size.to_le_bytes());
        h.update(self.rule_name.as_bytes());
        h.update(self.match_type.as_bytes());
        h.update(self.match_value.as_bytes());
        h.update(self.cmdline.as_bytes());
    }
}
